import assert from "node:assert/strict";import test from "node:test";import { readFileSync } from "node:fs";import { assertAliasAvailable,planAliasChange,profileChangeNeedsApproval,profileDecision,validateProfileName } from "./policy.ts";
test("normaler Nutzer ändert Alias sofort",()=>assert.deepEqual(planAliasChange("Alt","Neu",false),{mode:"IMMEDIATE",activeAlias:"Neu",requestedAlias:null}));
test("eingeschränkter Nutzer erzeugt Alias-Antrag und alter Alias bleibt aktiv",()=>assert.deepEqual(planAliasChange("Alt","Neu",true),{mode:"REQUEST",activeAlias:"Alt",requestedAlias:"Neu"}));
test("Alias-Kollision wird verhindert",()=>assert.throws(()=>assertAliasAvailable(false),/bereits verwendet/));
test("Namensänderung erzeugt immer einen Antrag",()=>{assert.equal(profileChangeNeedsApproval("NAME",false),true);assert.deepEqual(validateProfileName(" Ada "," Lovelace "),{firstName:"Ada",lastName:"Lovelace"})});
test("Admin genehmigt Namensänderung oder lehnt Profiländerung ab",()=>{assert.equal(profileDecision("PENDING","APPROVE"),"APPROVED");assert.equal(profileDecision("PENDING","REJECT"),"REJECTED")});
test("Navigation zeigt keinen Registrieren-Button, Anmeldung enthält Registrierungslink",()=>{const nav=readFileSync("app/navigation.tsx","utf8");const login=readFileSync("app/anmelden/page.tsx","utf8");assert.equal(nav.includes('href="/registrieren"'),false);assert.equal(login.includes("Noch kein Konto?"),true);assert.equal(login.includes('href="/registrieren"'),true)});
test("Nicht-Admin kann Profilanträge nicht bearbeiten",()=>{const actions=readFileSync("app/admin/profilantraege/actions.ts","utf8");assert.equal((actions.match(/requireAdmin\(\)/g)??[]).length>=2,true)});
test("Einschränkung und Antragsentscheidungen erzeugen AuditLogs",()=>{const admin=readFileSync("app/admin/actions.ts","utf8");const requests=readFileSync("app/admin/profilantraege/actions.ts","utf8");assert.equal(admin.includes("Profileinschränkung geändert"),true);assert.equal(requests.includes("auditLog.create"),true);assert.equal(requests.includes("AuditAction.APPROVED"),true);assert.equal(requests.includes("AuditAction.REJECTED"),true)});
