import assert from "node:assert/strict";
import test from "node:test";
import { calculateChronologicalRatings, type ChronologicalGame } from "../elo/timeline.ts";
import { canClaimPlayer, createClaimAssignment, planParticipationTransfer, validateMergeCandidates } from "./policy.ts";

test("Alias-Claim ist nur für unzugeordnete Spieler ohne offenen Claim möglich",()=>{assert.equal(canClaimPlayer({userId:null,pendingClaims:0}),true);assert.equal(canClaimPlayer({userId:"user-1",pendingClaims:0}),false);assert.equal(canClaimPlayer({userId:null,pendingClaims:1}),false)});
test("Alias-Claim erzeugt die korrekte Pending-Zuordnung",()=>assert.deepEqual(createClaimAssignment("user-1",{id:"player-1",userId:null,pendingClaims:0}),{playerId:"player-1",submittedByUserId:"user-1",status:"PENDING"}));
test("bereits geclaimter Spieler kann nicht erneut beansprucht werden",()=>assert.equal(canClaimPlayer({userId:null,pendingClaims:1}),false));
test("unterschiedliche bestehende User-Zuordnungen blockieren den Merge",()=>assert.throws(()=>validateMergeCandidates({id:"source",userId:"u1"},{id:"target",userId:"u2"}),/unterschiedlichen Benutzerkonten/));
test("nach einem Merge gehen keine Partieverknüpfungen verloren",()=>{const before=[{id:"p1",gameId:"g1",playerId:"source"},{id:"p2",gameId:"g2",playerId:"source"},{id:"p3",gameId:"g3",playerId:"target"}];const after=planParticipationTransfer("source","target",before);assert.equal(after.length,before.length);assert.equal(after.every(item=>item.playerId==="target"),true);assert.deepEqual(after.map(item=>item.id).sort(),before.map(item=>item.id).sort())});
test("Merge zweier Spieler verändert die spätere Elo chronologisch korrekt",()=>{const initial=new Map([["target",1500],["b",1500],["c",1500],["d",1500]]);const games:ChronologicalGame[]=[{id:"old",playedAt:new Date("2026-01-01"),createdAt:new Date("2026-01-02"),participants:["target","b","c","d"].map((playerId,index)=>({id:`old-${playerId}`,playerId,points:100-index,tiebreakRank:null}))},{id:"later",playedAt:new Date("2026-02-01"),createdAt:new Date("2026-02-02"),participants:["d","c","b","target"].map((playerId,index)=>({id:`later-${playerId}`,playerId,points:100-index,tiebreakRank:null}))}];const result=calculateChronologicalRatings(initial,games);const oldAfter=result.participantUpdates.find(item=>item.id==="old-target")!.ratingAfter;const laterBefore=result.participantUpdates.find(item=>item.id==="later-target")!.ratingBefore;assert.equal(laterBefore,oldAfter);assert.notEqual(laterBefore,1500)});
